# Generated by Django 5.2.13 on 2026-04-30 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_email_student_phone_alter_student_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='homework_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
