# Generated by Django 5.2.13 on 2026-04-30 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_grade_grade_grade_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(),
        ),
    ]
